global:
  environment: production

microservices:
  apiquotes:
    image: "harbor.kaze-cloud.fr/public/service-quotes:0.1"
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "256Mi"
    path: /quotes
    port: "5000"
  apisearch:
    image: "harbor.kaze-cloud.fr/public/service-search:0.1"
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "256Mi"
    path: /search
    port: "5000"
  apiusers:
    image: "harbor.kaze-cloud.fr/public/service-users:0.1"
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "256Mi"
    path: /users
    port: "5000"

redis:
  host: "redis"
  port: "6379"
  replicas: 1
  image: bitnami/redis:latest
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  service:
    type: ClusterIP
  pvc:
    accessMode: ReadWriteOnce
    storage: 5Gi

ingress:
  enabled: true
  host: sae503-helm.kaze-cloud.fr
