apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sae503-dev.kaze-cloud.fr`) && PathPrefix(`/quotes`)
      kind: Rule
      services:
        - name: api-quotes
          port: 5000
      middlewares:
        - name: ratelimit
    - match: Host(`sae503-dev.kaze-cloud.fr`) && PathPrefix(`/users`)
      kind: Rule
      services:
        - name: api-users
          port: 5000
      middlewares:
        - name: ratelimit
    - match: Host(`sae503-dev.kaze-cloud.fr`) && PathPrefix(`/search`)
      kind: Rule
      services:
        - name: api-search
          port: 5000
      middlewares:
        - name: ratelimit