apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sae503-dev.kaze-cloud.fr`)
      kind: Rule
      services:
        - name: api-quotes
          port: 
      middlewares:
        - name: ratelimit
