apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-quotes
  labels:
    app: api-quotes
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.microservices.apiquotes.replicas }}
  selector:
    matchLabels:
      app: api-quotes
  template:
    metadata:
      labels:
        app: api-quotes
        environment: {{ .Values.global.environment }}
    spec:
      containers:
      - name: api-quotes
        image: {{ .Values.microservices.apiquotes.image }}
        ports:
        - containerPort: {{ .Values.microservices.apiquotes.port }}
        env:
        - name: ENVIRONMENT
          value: "{{ .Values.global.environment }}"
        - name: REDIS_HOST
          value: "{{ .Values.redis.host }}"
        - name: REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: APP_PORT
          value: "{{ .Values.microservices.apiquotes.port }}"
        resources:
          limits:
            cpu: {{ .Values.microservices.apiquotes.resources.limits.cpu }}
            memory: {{ .Values.microservices.apiquotes.resources.limits.memory }}
          requests:
            cpu: {{ .Values.microservices.apiquotes.resources.requests.cpu }}
            memory: {{ .Values.microservices.apiquotes.resources.requests.memory }}
