apiVersion: v1
kind: Service
metadata:
  name: api-search
  labels:
    app: api-search
    environment: {{ .Values.global.environment }}
spec:
  selector:
    app: api-search
  ports:
  - protocol: TCP
    port: {{ .Values.microservices.apiSearch.port }}
    targetPort: {{ .Values.microservices.apiSearch.port }}