apiVersion: v1
kind: Service
metadata:
  name: api-users
  labels:
    app: api-users
    environment: {{ .Values.global.environment }}
spec:
  selector:
    app: api-users
  ports:
    - protocol: TCP
      port: {{ index .Values.microservices.api-users.port }}
      targetPort: {{ index .Values.microservices.api-users.port }}