apiVersion: v1
kind: Service
metadata:
  name: api-quotes
  labels:
    app: api-quotes
    environment: {{ .Values.global.environment }}
spec:
  selector:
    app: api-quotes
  ports:
  - protocol: TCP
    port: {{ .Values.microservices.apiquotes.port }}
    targetPort: {{ .Values.microservices.apiquotes.port }}