apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-users
  labels:
    app: api-users
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.microservices.apiusers.replicas }}
  selector:
    matchLabels:
      app: api-users
  template:
    metadata:
      labels:
        app: api-users
        environment: {{ .Values.global.environment }}
    spec:
      containers:
      - name: api-users
        image: {{ .Values.microservices.apiusers.image }}
        ports:
        - containerPort: {{ .Values.microservices.apiusers.port }}
        env:
        - name: ENVIRONMENT
          value: "{{ .Values.global.environment }}"
        - name: REDIS_HOST
          value: "{{ .Values.redis.host }}"
        - name: REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: APP_PORT
          value: "{{ .Values.microservices.apiusers.port }}"
        resources:
          limits:
            cpu: {{ .Values.microservices.apiusers.resources.limits.cpu }}
            memory: {{ .Values.microservices.apiusers.resources.limits.memory }}
          requests:
            cpu: {{ .Values.microservices.apiusers.resources.requests.cpu }}
            memory: {{ .Values.microservices.apiusers.resources.requests.memory }}
