apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    app: redis
spec:
  accessModes:
  - {{ .Values.redis.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.redis.pvc.storage }}
